#ifndef WEBUI_HTML_H
#define WEBUI_HTML_H

static const char WEBUI_HTML[] =
"<!DOCTYPE html><html lang='en'><head>"
"<meta charset='utf-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>WiFiend Remote</title>"
"<style>"
":root{"
"--bg:#000111;--bg2:#1A1A1F;--card:#2A2D31;"
"--title:#FAA307;--val:#FFFF00;--ctrl:#00FFFF;"
"--muted:#9CA3AF;--label:#D1D5DB;--light:#F4F6F8;"
"--danger:#FF4444;--ok:#22C55E;"
"}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{background:var(--bg);color:var(--light);font-family:-apple-system,system-ui,sans-serif;min-height:100vh;padding-bottom:84px}"
"header{background:var(--bg2);padding:12px 16px;border-bottom:1px solid var(--card);display:flex;align-items:center;gap:10px;position:sticky;top:0;z-index:10}"
"header h1{color:var(--title);font-size:20px;font-weight:700;flex:1}"
"#dot{width:10px;height:10px;border-radius:50%;background:#444;transition:background .3s}"
"#dot.on{background:var(--ctrl);box-shadow:0 0 6px var(--ctrl)}"
"#batt{font-size:12px;color:var(--muted)}"
"nav{display:flex;background:var(--bg2);border-bottom:1px solid var(--card);overflow-x:auto}"
"nav button{flex:1;min-width:70px;padding:10px 4px;background:none;border:none;border-bottom:2px solid transparent;"
"color:var(--muted);font-size:13px;cursor:pointer;white-space:nowrap;transition:color .2s}"
"nav button.active{color:var(--ctrl);border-bottom-color:var(--ctrl)}"
"nav button:hover{color:var(--light)}"
".panel{display:none;padding:14px;max-width:640px;margin:0 auto}"
".panel.active{display:block}"
".card{background:var(--card);border-radius:8px;padding:14px;margin-bottom:12px;border:1px solid #333}"
".card-title{color:var(--title);font-size:14px;font-weight:600;margin-bottom:10px}"
".row{display:flex;justify-content:space-between;align-items:center;margin-bottom:6px}"
".lbl{color:var(--label);font-size:12px}"
".val{color:var(--val);font-family:monospace;font-size:13px}"
".btn{background:none;border:1px solid var(--ctrl);color:var(--ctrl);padding:8px 14px;"
"border-radius:6px;cursor:pointer;font-size:13px;font-weight:500;transition:background .15s,color .15s}"
".btn:hover{background:var(--ctrl);color:var(--bg)}"
".btn:active{background:var(--ctrl);color:var(--bg)}"
".btn.danger{border-color:var(--danger);color:var(--danger)}"
".btn.danger:hover{background:var(--danger);color:#fff}"
".btn.ok{border-color:var(--ok);color:var(--ok)}"
".btn.ok:hover{background:var(--ok);color:#fff}"
".btn.sm{padding:5px 10px;font-size:12px}"
".btn-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}"
".sec-btn{display:flex;gap:8px;margin-bottom:12px}"
".sec-btn button{flex:1;padding:8px;border-radius:6px;border:1px solid #444;background:none;"
"color:var(--muted);font-size:13px;cursor:pointer;transition:all .2s}"
".sec-btn button.active{border-color:var(--ctrl);color:var(--ctrl);background:#00ffff11}"
"input[type=text],input[type=password]{width:100%;padding:9px 12px;background:#111;border:1px solid #444;"
"border-radius:6px;color:var(--light);font-size:14px;margin-bottom:8px}"
"input:focus{outline:none;border-color:var(--ctrl)}"
".ap-list{list-style:none}"
".ap-item{background:var(--card);border:1px solid #333;border-radius:8px;padding:12px;margin-bottom:8px}"
".ap-ssid{color:var(--title);font-size:15px;font-weight:600;margin-bottom:4px}"
".ap-meta{color:var(--val);font-family:monospace;font-size:12px;margin-bottom:8px}"
".ap-item.selected{border-color:var(--ctrl)}"
".status-card{background:#0a0a0a;border:1px solid #333;border-radius:6px;padding:10px;margin-top:10px;font-family:monospace;font-size:12px}"
".status-ok{color:var(--ok)}.status-err{color:var(--danger)}.status-busy{color:var(--val)}"
".rssi-bar{display:inline-flex;gap:1px;align-items:flex-end;height:12px;margin-right:6px}"
".rssi-bar span{width:3px;background:#333;border-radius:1px}"
".rssi-bar span.on{background:var(--ctrl)}"
".cap-item{background:var(--card);border:1px solid #333;border-radius:8px;padding:10px;margin-bottom:8px}"
".cap-type{display:inline-block;padding:2px 7px;border-radius:4px;font-size:11px;font-weight:600;margin-bottom:6px}"
".cap-type.P{background:#1f6feb;color:#fff}.cap-type.H{background:#238636;color:#fff}"
".cap-ssid{color:var(--title);font-size:14px;font-weight:600;margin-bottom:3px}"
".cap-mac{font-family:monospace;color:var(--muted);font-size:11px;margin-bottom:6px}"
"a.dl-btn{display:inline-block;background:none;border:1px solid var(--ctrl);color:var(--ctrl);"
"text-decoration:none;padding:5px 10px;border-radius:6px;font-size:12px}"
"a.dl-btn:hover{background:var(--ctrl);color:var(--bg)}"
"a.dl-btn.alt{border-color:#1f6feb;color:#388bfd}"
"a.dl-btn.alt:hover{background:#1f6feb;color:#fff}"
".empty{color:var(--muted);text-align:center;padding:24px;font-size:14px}"
"#toast{position:fixed;bottom:96px;left:50%;transform:translateX(-50%);"
"background:var(--bg2);border:1px solid var(--ctrl);color:var(--ctrl);"
"padding:10px 20px;border-radius:8px;font-size:13px;display:none;z-index:101;"
"white-space:nowrap;box-shadow:0 4px 16px rgba(0,255,255,.15)}"
"#toast.err{border-color:var(--danger);color:var(--danger)}"
"#logpanel{position:fixed;left:0;right:0;bottom:0;background:#000;color:#7fff7f;"
"font-family:Menlo,Consolas,monospace;font-size:11px;line-height:1.35;"
"border-top:1px solid #234;padding:6px 10px;max-height:80px;overflow-y:auto;"
"z-index:100;white-space:pre-wrap;word-break:break-all}"
"#logpanel .ts{color:#5a8aff;margin-right:6px}"
"#logpanel .empty{color:#446;font-style:italic}"
".sub-nav{display:flex;gap:6px;margin-bottom:14px;flex-wrap:wrap}"
".sub-nav button{padding:6px 12px;border-radius:6px;border:1px solid #444;background:none;"
"color:var(--muted);font-size:12px;cursor:pointer;transition:all .2s}"
".sub-nav button.active{border-color:var(--ctrl);color:var(--ctrl);background:#00ffff11}"
".sub-panel{display:none}.sub-panel.active{display:block}"
".section-title{color:var(--label);font-size:12px;text-transform:uppercase;letter-spacing:.5px;margin-bottom:10px}"
".sniff-item{font-family:monospace;font-size:12px;color:var(--val);padding:4px 0;border-bottom:1px solid #222}"
".sniff-item:last-child{border-bottom:none}"
"</style></head>"
"<body>"
"<header>"
"<h1>WiFiend Remote</h1>"
"<span id='batt'></span>"
"<span id='dot'></span>"
"</header>"
"<nav>"
"<button class='active' onclick='showTab(0,this)'>Scan</button>"
"<button onclick='showTab(1,this)'>Capture</button>"
"<button onclick='showTab(2,this)'>Tools</button>"
"<button onclick='showTab(3,this)'>BLE</button>"
"<button onclick='showTab(4,this)'>System</button>"
"</nav>"

/* ===== TAB 0: SCAN ===== */
"<div id='t0' class='panel active'>"
"<div class='card'>"
"<div class='card-title'>WiFi Scan</div>"
"<div class='btn-row'>"
"<button class='btn' onclick='startWifiScan()'>Run Scan</button>"
"<button class='btn' onclick='cmd({cmd:\"scan_get\"})'>Refresh</button>"
"</div>"
"<div id='scan-status' class='status-card' style='display:none'></div>"
"</div>"
"<div id='scan-count' class='lbl' style='margin-bottom:8px'></div>"
"<ul id='ap-list' class='ap-list'></ul>"
"</div>"

/* ===== TAB 1: CAPTURE ===== */
"<div id='t1' class='panel'>"
"<div class='sec-btn'>"
"<button id='cap-pmkid-btn' class='active' onclick='capMode(\"pmkid\",this)'>PMKID Hunt</button>"
"<button id='cap-hs-btn' onclick='capMode(\"hs\",this)'>Handshake Hunt</button>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Target AP</div>"
"<div id='cap-ap-picker'><div class='empty'>Run a scan first</div></div>"
"</div>"
"<div class='card' id='cap-ctrl-card'>"
"<div class='card-title'>Control</div>"
"<div class='btn-row'>"
"<button class='btn ok' id='cap-start-btn' onclick='capStart()'>Start Hunt</button>"
"<button class='btn danger' onclick='capStop()'>Stop</button>"
"<button class='btn' id='cap-deauth-btn' style='display:none' onclick='cmd({cmd:\"hs_deauth\"})'>Fire Deauth</button>"
"</div>"
"<div id='cap-status' class='status-card' style='margin-top:10px'><span class='status-busy'>Idle</span></div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Saved Captures</div>"
"<div class='btn-row' style='margin-bottom:10px'>"
"<a href='/pmkid.log' class='dl-btn alt' download='wifiend-pmkid.hc22000'>All PMKID</a>"
"<a href='/handshakes.log' class='dl-btn alt' download='wifiend-handshakes.hc22000'>All Handshakes</a>"
"</div>"
"<div id='cap-list'><div class='empty'>No captures yet</div></div>"
"</div>"
"</div>"

/* ===== TAB 2: TOOLS ===== */
"<div id='t2' class='panel'>"
"<div class='card' style='border-color:#3a3d41'>"
"<div class='lbl'>Deauth and Clone AP run on the device itself — use the encoder menu. "
"They take over the single radio, which would drop this Wi-Fi link. The dashboard "
"stays on the tools below that keep your connection alive.</div>"
"</div>"
"<div class='sub-nav'>"
"<button class='active' onclick='atkMode(\"sniff\",this)'>Sniffer</button>"
"<button onclick='atkMode(\"sta\",this)'>STA Connect</button>"
"</div>"

/* Sniffer sub-panel */
"<div id='atk-sniff' class='sub-panel active'>"
"<div class='card'>"
"<div class='card-title'>Client Sniffer</div>"
"<div class='btn-row'>"
"<button class='btn' onclick='cmd({cmd:\"sniff_start\"})'>Start Sniff</button>"
"<button class='btn danger' onclick='cmd({cmd:\"sniff_stop\"})'>Stop</button>"
"</div>"
"<div id='sniff-status' class='status-card' style='margin-top:10px'><span class='status-busy'>Idle</span></div>"
"<div id='sniff-list' style='margin-top:8px'></div>"
"</div>"
"</div>"

/* STA Connect sub-panel */
"<div id='atk-sta' class='sub-panel'>"
"<div class='card'>"
"<div class='card-title'>STA Connect</div>"
"<div class='section-title'>Select Network</div>"
"<div id='sta-picker'><div class='empty'>Run a scan first</div></div>"
"<div id='sta-pw-section' style='margin-top:8px'>"
"<input type='password' id='sta-pw' placeholder='Password (leave blank if open)'>"
"</div>"
"<div class='btn-row'>"
"<button class='btn ok' onclick='staConnect()'>Connect</button>"
"<button class='btn danger' onclick='cmd({cmd:\"sta_stop\"})'>Disconnect</button>"
"</div>"
"<div id='sta-status' class='status-card' style='margin-top:10px'><span class='status-busy'>Idle</span></div>"
"</div>"
"</div>"
"</div>"

/* ===== TAB 3: BLE ===== */
"<div id='t3' class='panel'>"
"<div class='card'>"
"<div class='card-title'>BLE Devices</div>"
"<div class='btn-row'>"
"<button class='btn' onclick='cmd({cmd:\"ble_scan_start\"})'>Scan BLE</button>"
"<button class='btn danger' onclick='cmd({cmd:\"ble_scan_stop\"})'>Stop</button>"
"</div>"
"<div id='ble-status' class='status-card' style='margin-top:10px'><span class='status-busy'>Idle</span></div>"
"<div id='ble-count' class='lbl' style='margin:8px 0'></div>"
"<div id='ble-list'></div>"
"</div>"
"</div>"

/* ===== TAB 4: SYSTEM ===== */
"<div id='t4' class='panel'>"
"<div class='card'>"
"<div class='card-title'>Device Info</div>"
"<div class='row'><span class='lbl'>MAC</span><span class='val' id='sys-mac'>--</span></div>"
"<div class='row'><span class='lbl'>Heap</span><span class='val' id='sys-heap'>--</span></div>"
"<div class='row'><span class='lbl'>Flash</span><span class='val' id='sys-flash'>--</span></div>"
"<div class='row'><span class='lbl'>Uptime</span><span class='val' id='sys-uptime'>--</span></div>"
"<div class='row'><span class='lbl'>Battery</span><span class='val' id='sys-batt'>--</span></div>"
"<div class='row'><span class='lbl'>IDF</span><span class='val' id='sys-idf'>--</span></div>"
"<div class='row'><span class='lbl'>Captures</span><span class='val' id='sys-caps'>--</span></div>"
"<div class='row'><span class='lbl'>Firmware</span><span class='val' id='sys-fw'>--</span></div>"
"<div class='row'><span class='lbl'>OTA slot</span><span class='val' id='sys-ota'>--</span></div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Check for Update</div>"
"<div class='lbl' id='fwver' style='margin-bottom:10px'>Firmware --</div>"
"<input type='text' id='home_ssid' maxlength='32' placeholder='Home Wi-Fi SSID' style='margin-bottom:8px;width:100%'>"
"<input type='password' id='home_pass' maxlength='63' placeholder='Home Wi-Fi password (leave blank to keep)' style='margin-bottom:8px;width:100%'>"
"<div class='btn-row'>"
"<button class='btn ok' onclick='otaCheckUpdate()'>Check for Update</button>"
"</div>"
"<div class='lbl' style='margin-top:8px'>Reboots, joins your Wi-Fi, and installs a newer GitHub release if one exists. Watch the OLED.</div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Manual Upload</div>"
"<input type='file' id='ota-file' accept='.bin,application/octet-stream'>"
"<div class='btn-row'>"
"<button class='btn' onclick='otaUpload()'>Upload &amp; Reboot</button>"
"</div>"
"<div id='ota-status' class='status-card' style='display:none;margin-top:10px'></div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Downloads</div>"
"<div class='btn-row'>"
"<a href='/pmkid.log' class='dl-btn alt' download='wifiend-pmkid.hc22000'>PMKID Log</a>"
"<a href='/handshakes.log' class='dl-btn alt' download='wifiend-handshakes.hc22000'>Handshakes Log</a>"
"</div>"
"</div>"
"<div class='card'>"
"<div class='card-title'>Remote Session</div>"
"<div class='btn-row'>"
"<button class='btn danger' onclick='cmd({cmd:\"exit\"})'>Exit to Menu</button>"
"</div>"
"<div class='lbl' style='margin-top:8px'>Sends device back to its main menu and closes this AP.</div>"
"</div>"
"</div>"

"<div id='toast'></div>"
"<div id='logpanel'><div class='empty'>activity log — actions will appear here</div></div>"

"<script>"
"var ws,toastTimer;"
"var scanAps=[];"
"var selCapAp=null,selStaAp=null;"
"var capCurrentMode='pmkid';"

/* ---- WebSocket ---- */
"function connect(){"
"ws=new WebSocket('ws://'+location.host+'/ws');"
"ws.onopen=function(){document.getElementById('dot').classList.add('on');send({cmd:'get_state'});};"
"ws.onclose=function(){document.getElementById('dot').classList.remove('on');showToast('Reconnecting…');setTimeout(connect,2000);};"
"ws.onerror=function(){ws.close();};"
"ws.onmessage=function(e){try{dispatch(JSON.parse(e.data));}catch(x){}};"
"}"
"function send(o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o));}"
"function cmd(o){send(o);}"
"function startWifiScan(){"
"var el=document.getElementById('scan-status');"
"el.style.display='block';"
"el.innerHTML='<span class=\"status-busy\">Scanning APs… SoftAP stays up</span>';"
"showToast('Scanning APs…');"
"cmd({cmd:'scan_start'});"
"}"

/* ---- Toast ---- */
"function showToast(msg,err){"
"var t=document.getElementById('toast');"
"t.textContent=msg;t.style.display='block';"
"t.className=err?'err':'';"
"clearTimeout(toastTimer);"
"if(!err)toastTimer=setTimeout(function(){t.style.display='none';},3000);"
"}"
"function hideToast(){document.getElementById('toast').style.display='none';}"

/* ---- Tab switching ---- */
"function showTab(n,btn){"
"for(var i=0;i<5;i++){document.getElementById('t'+i).classList.remove('active');}"
"document.getElementById('t'+n).classList.add('active');"
"var btns=document.querySelectorAll('nav button');"
"btns.forEach(function(b){b.classList.remove('active');});"
"btn.classList.add('active');"
"}"

/* ---- RSSI bar helper ---- */
"function rssiBar(rssi){"
"var lvl=rssi>=-50?4:rssi>=-65?3:rssi>=-75?2:1;"
"var h=['4','6','9','12'];var s='';"
"for(var i=0;i<4;i++){s+='<span style=\"height:'+h[i]+'px'+(i<lvl?';background:var(--ctrl)':'')+'\"></span>';}"
"return '<span class=\"rssi-bar\">'+s+'</span>';"
"}"

/* ---- Security label ---- */
"function secLabel(s){"
"var m=['Open','WEP','WPA','WPA2','WPA/WPA2','WPA3','WPA2/WPA3','WAPI','OWE','MAX'];"
"return m[s]||'?';"
"}"

/* ---- Render scan results ---- */
"function renderAps(aps){"
"scanAps=aps||[];"
"var el=document.getElementById('ap-list');"
"document.getElementById('scan-count').textContent=scanAps.length+' network'+(scanAps.length===1?'':'s')+' found';"
"if(!scanAps.length){el.innerHTML='<li class=\"empty\">No APs found — run a scan</li>';return;}"
"var h='';"
"scanAps.forEach(function(ap,i){"
"h+='<li class=\"ap-item\" id=\"ap-'+i+'\">';"
"h+='<div class=\"ap-ssid\">'+escHtml(ap.ssid||'(hidden)')+'</div>';"
"h+='<div class=\"ap-meta\">'+rssiBar(ap.rssi)+ap.rssi+'dBm &nbsp;Ch:'+ap.channel+' &nbsp;'+secLabel(ap.security)+'<br>'+ap.bssid+'</div>';"
"h+='<div class=\"btn-row\">';"
"h+='<button class=\"btn sm\" onclick=\"selectCap('+i+')\">Capture</button>';"
"h+='</div></li>';"
"});"
"el.innerHTML=h;"
"rebuildPickers();"
"}"

/* ---- Picker helpers ---- */
"function pickerHtml(idPrefix,onSel){"
"if(!scanAps.length)return '<div class=\"empty\">Run a scan first</div>';"
"var h='';"
"scanAps.forEach(function(ap,i){"
"h+='<div class=\"ap-item\" id=\"'+idPrefix+'-'+i+'\" onclick=\"('+onSel+')('+i+')\" style=\"cursor:pointer\">';"
"h+='<div class=\"ap-ssid\">'+escHtml(ap.ssid||'(hidden)')+'</div>';"
"h+='<div class=\"ap-meta\">'+rssiBar(ap.rssi)+ap.rssi+'dBm &nbsp;Ch:'+ap.channel+'</div>';"
"h+='</div>';"
"});"
"return h;"
"}"
"function rebuildPickers(){"
"document.getElementById('cap-ap-picker').innerHTML=pickerHtml('cap-ap','selectCap');"
"document.getElementById('sta-picker').innerHTML=pickerHtml('sta-ap','selectSta');"
"}"
"function highlightPicker(prefix,idx){"
"document.querySelectorAll('[id^=\"'+prefix+'-\"]').forEach(function(el){el.classList.remove('selected');});"
"var el=document.getElementById(prefix+'-'+idx);"
"if(el)el.classList.add('selected');"
"}"
"function selectCap(i){selCapAp=scanAps[i];highlightPicker('cap-ap',i);}"
"function selectSta(i){selStaAp=scanAps[i];highlightPicker('sta-ap',i);}"

/* ---- Capture mode toggle ---- */
"function capMode(mode,btn){"
"capCurrentMode=mode;"
"document.querySelectorAll('.sec-btn button').forEach(function(b){b.classList.remove('active');});"
"btn.classList.add('active');"
"document.getElementById('cap-deauth-btn').style.display=(mode==='hs')?'':'none';"
"}"
"function capStart(){"
"if(!selCapAp){showToast('Select a target AP first',true);return;}"
"if(capCurrentMode==='pmkid')cmd({cmd:'pmkid_start',bssid:selCapAp.bssid});"
"else cmd({cmd:'hs_start',bssid:selCapAp.bssid});"
"}"
"function capStop(){"
"if(capCurrentMode==='pmkid')cmd({cmd:'pmkid_stop'});"
"else cmd({cmd:'hs_stop'});"
"}"

/* ---- Tools sub-panel toggle ---- */
"var atkPanels=['sniff','sta'];"
"function atkMode(mode,btn){"
"atkPanels.forEach(function(p){document.getElementById('atk-'+p).classList.remove('active');});"
"document.getElementById('atk-'+mode).classList.add('active');"
"document.querySelectorAll('.sub-nav button').forEach(function(b){b.classList.remove('active');});"
"btn.classList.add('active');"
"}"
"function staConnect(){"
"if(!selStaAp){showToast('Select a network first',true);return;}"
"var pw=document.getElementById('sta-pw').value;"
"cmd({cmd:'sta_connect',ssid:selStaAp.ssid,bssid:selStaAp.bssid,password:pw});"
"}"

/* ---- Renders for captures list ---- */
"function renderCaptures(caps){"
"var el=document.getElementById('cap-list');"
"if(!caps||!caps.length){el.innerHTML='<div class=\"empty\">No captures yet</div>';return;}"
"var h='';"
"caps.forEach(function(c,i){"
"h+='<div class=\"cap-item\">';"
"h+='<span class=\"cap-type '+c.type+'\">'+((c.type==='P')?'PMKID':'Handshake')+'</span>';"
"h+='<div class=\"cap-ssid\">'+escHtml(c.ssid||'(hidden)')+'</div>';"
"h+='<div class=\"cap-mac\">BSSID: '+c.bssid+'</div>';"
"h+='<a href=\"/entry?i='+c.index+'\" class=\"dl-btn\" download=\"wifiend-'+((c.type==='P')?'pmkid':'hs')+'-'+i+'.hc22000\">Download</a>';"
"h+='</div>';"
"});"
"el.innerHTML=h;"
"}"

/* ---- Sys info ---- */
"function renderSys(d){"
"setText('sys-mac',d.mac||'--');"
"setText('sys-heap',(d.heap_kb||0)+' KB free');"
"setText('sys-flash',(d.flash_mb||0)+' MB');"
"var up=d.uptime_s||0;"
"var h=Math.floor(up/3600),m=Math.floor((up%3600)/60),s=up%60;"
"setText('sys-uptime',(h?h+'h ':'')+(m?m+'m ':'')+s+'s');"
"setText('sys-batt',d.battery_pct!=null?d.battery_pct+'%':'--');"
"setText('sys-idf',d.idf_ver||'--');"
"setText('sys-caps',(d.capture_count||0)+' saved');"
"setText('sys-ota',d.ota_slot||'--');"
"setText('sys-fw',d.fw||'--');"
"setText('fwver','Firmware '+(d.fw||'--'));"
"var hs=document.getElementById('home_ssid');"
"if(hs&&d.home_ssid&&!hs.value)hs.value=d.home_ssid;"
"if(d.battery_pct!=null)document.getElementById('batt').textContent=d.battery_pct+'%';"
"if(d.ble_devices)renderBle(d.ble_devices,d.ble_scanning);"
"}"

/* ---- Dispatch ---- */
"function dispatch(m){"
"switch(m.event){"
"case 'state':"
"renderAps(m.aps);"
"renderSys(m);"
"loadCaptures();"
"hideToast();"
"break;"
"case 'scan_done':"
"renderAps(m.aps);"
"document.getElementById('scan-status').style.display='none';"
"showToast('Scan complete — '+m.aps.length+' APs found');"
"break;"
"case 'wifi_restarting':"
"showToast('WiFi restarting… reconnecting');"
"break;"
"case 'wifi_ready':"
"showToast('Back online');"
"break;"
"case 'sniff_update':"
"renderSniff(m);"
"break;"
"case 'pmkid_update':"
"renderCapStatus('cap-status',m);"
"break;"
"case 'hs_update':"
"renderCapStatus('cap-status',m);"
"break;"
"case 'sta_update':"
"var sc={'connecting':'<span class=\"status-busy\">Connecting…</span>',"
"'connected':'<span class=\"status-ok\">Connected: '+escHtml(m.ip||'')+'</span>',"
"'failed':'<span class=\"status-err\">Failed</span>'};"
"setHtml('sta-status',sc[m.state]||'<span class=\"status-busy\">Idle</span>');"
"break;"
"case 'capture_saved':"
"loadCaptures();"
"showToast((m.type==='P'?'PMKID':'Handshake')+' captured: '+escHtml(m.ssid||''));"
"break;"
"case 'server_stopping':"
"showToast('Server stopping…',true);"
"appendLog('server stopping');"
"break;"
"case 'log':"
"appendLog(m.msg);"
"break;"
"case 'ble_update':"
"renderBle(m.devices||[],m.scanning);"
"break;"
"case 'ota':"
"renderOta(m);"
"break;"
"}"
"}"

"function appendLog(msg){"
"var p=document.getElementById('logpanel');"
"var em=p.querySelector('.empty');if(em)em.remove();"
"var ts=new Date();"
"var hh=String(ts.getHours()).padStart(2,'0');"
"var mm=String(ts.getMinutes()).padStart(2,'0');"
"var ss=String(ts.getSeconds()).padStart(2,'0');"
"var line=document.createElement('div');"
"line.innerHTML='<span class=\"ts\">'+hh+':'+mm+':'+ss+'</span>'+escHtml(msg);"
"p.appendChild(line);"
"while(p.children.length>30)p.removeChild(p.firstChild);"
"p.scrollTop=p.scrollHeight;"
"}"

"function renderCapStatus(elId,m){"
"var col=m.state==='captured'?'status-ok':m.state==='failed'?'status-err':'status-busy';"
"var msg=m.state==='captured'?"
"'Captured! SSID: '+escHtml(m.target||''):"
"'State: '+m.state+' Frames: '+(m.frames||0);"
"setHtml(elId,'<span class=\"'+col+'\">'+msg+'</span>');"
"}"
"function renderSniff(m){"
"setHtml('sniff-status','<span class=\"status-ok\">Sniffing — '+m.count+' clients</span>');"
"var h='';"
"(m.clients||[]).forEach(function(c){"
"h+='<div class=\"sniff-item\">'+c.mac+' &nbsp; Ch:'+c.channel+' &nbsp; '+c.rssi+'dBm</div>';"
"});"
"document.getElementById('sniff-list').innerHTML=h;"
"}"
"function renderBle(devs,scanning){"
"setHtml('ble-status',scanning?'<span class=\"status-ok\">Scanning…</span>':'<span class=\"status-busy\">Idle</span>');"
"setText('ble-count',(devs?devs.length:0)+' device'+(devs&&devs.length===1?'':'s'));"
"var el=document.getElementById('ble-list');"
"if(!devs||!devs.length){el.innerHTML='<div class=\"empty\">No devices — tap Scan BLE</div>';return;}"
"var h='';"
"devs.forEach(function(d){"
"h+='<div class=\"ap-item\"><div class=\"ap-ssid\">'+escHtml(d.name||'(unnamed)')+'</div>';"
"h+='<div class=\"ap-meta\">'+rssiBar(d.rssi)+d.rssi+'dBm &nbsp;'+escHtml(d.type||'?')+'<br>'+d.addr+'</div></div>';"
"});"
"el.innerHTML=h;"
"}"
"function renderOta(m){"
"var st=document.getElementById('ota-status');"
"st.style.display='block';"
"if(m.state==='writing')st.innerHTML='<span class=\"status-busy\">Uploading '+m.percent+'%</span>';"
"else if(m.state==='done')st.innerHTML='<span class=\"status-ok\">Complete — rebooting…</span>';"
"else if(m.state==='error')st.innerHTML='<span class=\"status-err\">'+escHtml(m.msg||'Failed')+'</span>';"
"else if(m.state==='start')st.innerHTML='<span class=\"status-busy\">Starting upload…</span>';"
"}"
"function otaCheckUpdate(){"
"var ssid=document.getElementById('home_ssid').value.trim();"
"var pass=document.getElementById('home_pass').value;"
"if(!ssid){showToast('Enter home Wi-Fi SSID',true);return;}"
"if(!confirm('Reboot and check GitHub for a newer release? Watch the device screen.'))return;"
"showToast('Leaving WebUI — joining home Wi-Fi…');"
"fetch('/update',{method:'POST',headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({ssid:ssid,pass:pass})})"
".then(function(r){return r.json();})"
".then(function(j){if(!j.ok)showToast(j.error||'Update failed',true);})"
".catch(function(){});"
"}"
"function otaUpload(){"
"var f=document.getElementById('ota-file').files[0];"
"if(!f){showToast('Select a .bin file',true);return;}"
"renderOta({state:'start'});"
"fetch('/ota',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:f})"
".then(function(r){return r.json();})"
".then(function(j){"
"if(!j.ok){renderOta({state:'error',msg:j.msg||'Upload failed'});showToast(j.msg||'OTA failed',true);}"
"})"
".catch(function(){renderOta({state:'error',msg:'Network error'});showToast('OTA failed',true);});"
"}"

/* ---- Load captures via JSON ---- */
"function loadCaptures(){"
"fetch('/captures').then(function(r){return r.json();}).then(function(d){renderCaptures(d);}).catch(function(){});"
"}"

/* ---- Util ---- */
"function setText(id,v){var e=document.getElementById(id);if(e)e.textContent=v;}"
"function setHtml(id,v){var e=document.getElementById(id);if(e)e.innerHTML=v;}"
"function escHtml(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');}"

"connect();"
"</script>"
"</body></html>";

#endif
